name: Containers

on:
  push:
    branches: [ master ]

jobs:
  containers:
    name: "Publishing containers"
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: 'joostschriek'
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Publish images
        uses: docker/build-push-action@v2
        with:
          context: ./src
          registry: docker.pkg.github.com
          tags: |
            joostschriek/gitman:latest
            ghcr.io/joostschriek/gitman:latest
          push: true
          