name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Publish image to github
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: joostschriek/gitman/gitman
          tags: latest
          always_pull: true
          tag_with_ref: true
      - name: Publish image to dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: joostschriek
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
          repository: joostschriek/gitman
          tags: latest
          always_pull: true
          tag_with_ref: true